name: Build WebView Overlay

on:
  workflow_dispatch:
  push:
    branches: [ "main", "development" ]
  pull_request:
    branches: [ "main", "development" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Grant execute permission
      run: chmod +x "build.sh"
    - name: Install dependencies
      run: sudo apt install git xmlstarlet aapt apktool -y
    - name: Build overlay
      run: bash build.sh
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: Flashable ZIP
        path: build/BromiteSystemWebViewOverlay.zip
